-- TB_WRK_ALT_EXECUTIVE --
INSERT INTO TB_WRK_ALT_EXECUTIVE AS
SELECT 
	prp.ANOMESDIA,
	prp.ID_EXECUTIVE,
	prp.NM_EXECUTIVE,
	prp.ID_SAP,
	prp.DT_INIT,
	prp.DT_END,
	IF(ISNULL(dim.NM_EXECUTIVE),'I', 
	IF((prp.DT_END <> dim.DT_END),'E', 'N')) AS COD_INDCD_ALT
FROM TB_WRK_PREP_EXECUTIVE prp
LEFT JOIN DIM_EXECUTIVE dim
ON prp.ID_EXECUTIVE = dim.ID_EXECUTIVE;

-- TB_WRK_ALT_UN --
INSERT INTO TB_WRK_ALT_UN
SELECT
		prp.ANOMESDIA,
		prp.ID_UN,
		prp.NM_UN,
		prp.DT_INIT,
		prp.DT_END,
IF(ISNULL(dim.NM_UN),'I', 
IF((prp.DT_END <> dim.DT_END),'E', 'N')) AS COD_INDCD_ALT
FROM TB_WRK_PREP_UN prp
LEFT JOIN DIM_UN dim
ON prp.ID_UN = dim.ID_UN;

-- TB_WRK_ALT_EXT --
INSERT INTO TB_WRK_ALT_EXT
SELECT 
		prp.ANOMESDIA,
		prp.ID_EXT,
		prp.NM_EXT,
		prp.DT_INIT,
		prp.DT_END,
IF(ISNULL(dim.ID_EXT),'I', 
IF((prp.NM_EXT <> dim.NM_EXT),'A', 
IF((prp.DT_END <> dim.DT_END),'E','N'))) AS COD_INDCD_ALT
FROM TB_WRK_PREP_EXT prp
LEFT JOIN DIM_EXT dim
ON prp.ID_EXT = dim.ID_EXT;

-- TB_WRK_ALT_SQUAD --
INSERT INTO TB_WRK_ALT_SQUAD
SELECT 
		prp.ANOMESDIA,
		prp.ID_SQUAD,
		prp.NM_SQUAD,
		prp.DT_INIT,
		prp.DT_END,
IF(ISNULL(dim.ID_SQUAD),'I', 
IF((prp.NM_SQUAD <> dim.NM_SQUAD),'A', 
IF((prp.DT_END <> dim.DT_END),'E','N'))) AS COD_INDCD_ALT
FROM TB_WRK_PREP_SQUAD prp
LEFT JOIN DIM_SQUAD dim
ON prp.ID_SQUAD = dim.ID_SQUAD;




